CREATE OR ALTER PROCEDURE [sis].[ObtenerSexos]
AS BEGIN

	SELECT 
		CV.IDCATALOGOVALOR AS ID,
		CV.CODIGO,
		CV.NOMBRE
	FROM SIS.CATALOGOVALOR CV
	INNER JOIN SIS.CATALOGO C
		ON CV.IDCATALOGO = C.IDCATALOGO
		AND C.CODIGO = 'SEXO'

	RETURN 1;
END