CREATE OR ALTER PROCEDURE [per].[ObtenerClientesTotal]
	@Nombre VARCHAR(255)
AS BEGIN

	SELECT ISNULL(COUNT(C.IDCLIENTE), 0) AS Total
	FROM PER.CLIENTE C
	INNER JOIN PER.PERSONA P
		ON C.IDPERSONA = P.IDPERSONA
	INNER JOIN SIS.CATALOGOVALOR CV
		ON C.IDESTADO = CV.IDCATALOGOVALOR
		AND CV.CODIGO = 'ACT'
	WHERE @Nombre = '' OR (
		@Nombre != '' AND (
			( UPPER(P.PRIMERNOMBRE) LIKE '%' + UPPER(@Nombre) + '%' ) OR
			( P.SEGUNDONOMBRE IS NOT NULL AND UPPER(P.SEGUNDONOMBRE) LIKE '%' + UPPER(@Nombre) + '%' ) OR
			( UPPER(P.PRIMERAPELLIDO) LIKE '%' + UPPER(@Nombre) + '%' ) OR
			( UPPER(P.SEGUNDOAPELLIDO) LIKE '%' + UPPER(@Nombre) + '%' )
		)
	)

	RETURN 1;
END