CREATE OR ALTER PROCEDURE [tmp].[ActualizarDivisionPolitica]
AS
BEGIN
	
	-- Registro las provincias.
	INSERT INTO CFG.PROVINCIA (CODIGO, NOMBRE)
	SELECT CONVERT(VARCHAR(50), CODIGO), NOMBRE
	FROM TMP.PROVINCIA

	-- Registro los cantones.
	INSERT INTO CFG.CANTON (IDPROVINCIA, CODIGO, NOMBRE)
	SELECT PP.IDPROVINCIA, CONVERT(VARCHAR(50), C.CODIGO), C.NOMBRE
	FROM TMP.CANTON C
	INNER JOIN TMP.PROVINCIA P
		ON C.PROVINCIA = P.CODIGO
	INNER JOIN CFG.PROVINCIA PP
		ON PP.CODIGO = CONVERT(VARCHAR(50), P.CODIGO)

	-- Registro los distritos.
	INSERT INTO CFG.DISTRITO (IDCANTON, CODIGO, NOMBRE)
	SELECT CC.IDCANTON, CONVERT(VARCHAR(50), D.CODIGO), D.NOMBRE
	FROM TMP.DISTRITO D
	INNER JOIN TMP.CANTON C
		ON D.CANTON = C.CODIGO
	INNER JOIN CFG.CANTON CC
		ON CC.CODIGO = CONVERT(VARCHAR(50), C.CODIGO)

END