-- Se crea el catálogo de estados del cliente.
SET IDENTITY_INSERT SIS.CATALOGO ON;

IF NOT EXISTS (
	SELECT 1
	FROM SIS.CATALOGO
	WHERE CODIGO = 'ESTADOSCLIENTE'
)
BEGIN
	INSERT INTO SIS.CATALOGO (IDCATALOGO, CODIGO, NOMBRE)
	VALUES (10000, 'ESTADOSCLIENTE', 'Estados del cliente')
END

SET IDENTITY_INSERT SIS.CATALOGO OFF;

-- Se crean los valores de catalogo valor.
SET IDENTITY_INSERT SIS.CATALOGOVALOR ON;

INSERT INTO SIS.CATALOGOVALOR (IDCATALOGOVALOR, IDCATALOGO, CODIGO, NOMBRE)
VALUES  (10000000, 10000, 'ACT', 'Activo'),
		(10000001, 10000, 'INA', 'Inactivo'),
		(10000002, 10000, 'ELM', 'Eliminado')

SET IDENTITY_INSERT SIS.CATALOGOVALOR OFF;